### ISSUE TITLE
The following packages are incompatible with Storybook 8.2.9.

### ISSUE THREAD

**Issue by RomkaLTU** [stevensacks/storybook-next-intl#1]
The setup seems to work, but Storybook is giving warnings.

![image](https://github.com/user-attachments/assets/bc77dbb5-3c4b-4879-a11c-d865cf41d5ce)

**Comment by stevensacks** [comment]
I see the issue. Will fix.

**Comment by stevensacks** [comment]
Thanks for reporting. I believe this has been fixed in v1.1.2. Please try it out and let me know.
