### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by RomkaLTU** [stevensacks/storybook-next-intl#2]
I'm still determining when, but at some point, it stopped working, always giving this error on every story. 

![image](https://github.com/user-attachments/assets/c170fea8-4687-4a47-bc8f-98d888500b7d)

**Comment by stevensacks** [comment]
At the request of next-intl’s author, in the latest version, the name of the property you pass in the parameters has changed from `messages` to `messagesByLocale`. Check the README for the latest instructions.
