### ISSUE TITLE
Unable to use rich text in Storybook

### ISSUE THREAD

**Issue by krakz999** [stevensacks/storybook-next-intl#3]
When I try to use rich text in storybook, e.g.:

Translation text: `"Some text <link>this is the link label</link> end of text"`

To be used like this:

```
{t.rich("text", {
          link: (chunks) => (
              <a className="underline" href={myLink}>
                  {chunks}
              </a>
          ),
 })}
```

The text is not rendered, only the tag of the text. Even if I render it normally with t("text") it will still render the tag. It works otherwise, it is only an issue in Storybook.

What might be the problem?

**Comment by stevensacks** [comment]
That’s a question for @amann. I implemented the provider based on the official documentation.

https://github.com/amannn
