### ISSUE TITLE
Storybook : Next intl provider not found

### ISSUE THREAD

**Issue by Adam-Doria** [stevensacks/storybook-next-intl#4]
Hi, i'm trying to configure next-intl for storybook and use your addon.

unfortunattly i experience this error : 
![image](https://github.com/user-attachments/assets/3ca4d32a-6f51-42e7-9f89-7e4dde99520f)

I thought that Next intl provider is handle by your addon but i may be wrong and didn't catch the use of the addon.

Here are my files: 

main.ts 
![image](https://github.com/user-attachments/assets/330633a7-33e1-440a-ad66-3f053bad95a9)

next-intl.ts
![image](https://github.com/user-attachments/assets/9e3bd36a-a568-4f7e-a8a5-0be41554aff8)

previex.tsx
![image](https://github.com/user-attachments/assets/410d025c-a184-4a0a-8cbd-a8c5afcee767)

Also here the version i use: 
"storybook": "^8.2.6",
 "next": "14.2.5",
"next-intl": "^3.17.2",
"storybook-next-intl": "^1.1.4",

FYI in set  up next-intl without the app routing.

If you want any other information do no hesitate to ask

Thanks in advance for the help or any clue that could unlock me !

**Comment by Punie** [comment]
I'm having the exact same issue.

Right now, I'm handling it by adding the following to the decorators:
```ts
(Story, context) => {
  const locale = context.globals.locale;

  return (
    <NextIntlClientProvider
      locale={locale}
      messages={nextIntl.messagesByLocale[locale]}
    >
      <Story />
    </NextIntlClientProvider>
  );
}
```

But it was my understanding that this should not be necessary as this plugin should handle it for us.

**Comment by stevensacks** [comment]
Hm. This is odd. I'm already adding the provider here as per the next-intl docs: https://github.com/stevensacks/storybook-next-intl/blob/main/src/withNextIntl.tsx

Could you try updating your version of Storybook to the latest 8.3.x?

**Comment by Adam-Doria** [comment]
I just updated the last version of storybook and have the same issue.

@Punie Solution helped me to resolve the issue (thanks a lot, i was driving me crazy for days)

Is the error could come from you using IntlProvider and not NextIntlClientProvider ?

**Comment by Punie** [comment]
Yeah, for me too, I'm on latest version of Storybook (8.3.5)

**Comment by stevensacks** [comment]
The next-intl docs regarding putting it in Storybook say to use the one I’m using, and the example story in this addon’s repo is working, so it’s a bit confusing why it’s not working.

I’ll try switching to the provider you’re using, and if it still works in the example story, I’ll release it to see if that solves the issue.

**Comment by stevensacks** [comment]
https://github.com/stevensacks/storybook-next-intl/releases/tag/v1.1.6

Hope this resolves the issue!

**Comment by Adam-Doria** [comment]
Hello, it's working perfectly since you changed the provider for <NextIntProvider> .

Thanks !
