### ISSUE TITLE
Error with Next.js 15 + Storybook 8.4

### ISSUE THREAD

**Issue by robcaldecott** [stevensacks/storybook-next-intl#5]
We are upgrading our project to use Next.js 15 and are facing the following error in Storybook for all components, even those that are not using `next-intl` functionality:

```
A React Element from an older version of React was rendered. This is not supported. It can happen if:
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the [Decorators documentation](https://storybook.js.org/docs/writing-stories/decorators).
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring [Webpack](https://storybook.js.org/docs/builders/webpack) or [Vite](https://storybook.js.org/docs/builders/vite) with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the [Environment Variables documentation](https://storybook.js.org/docs/configure/environment-variables).
```

If we remove the `storybook-next-intl` from our Storybook config then components that do not consume `useTranslations` will render fine, but obviously intl-aware components will fail with a different error:

```
Failed to call `useTranslations` because the context from `NextIntlClientProvider` was not found.
```

Any ideas for a workaround, even if we can mock `NextIntlClientProvider` somehow, are welcome.

**Comment by robcaldecott** [comment]
For now we can remove the add-on and add a global decorator, but we lose the ability to switch locales.

**preview.tsx**
```tax
import { NextIntlClientProvider } from "next-intl";
import type { Preview } from "@storybook/react";
import en from "../src/messages/en.json";

const preview: Preview = {
  decorators: [
    (Story) => (
      <NextIntlClientProvider locale="en" messages={en}>
        <Story />
      </NextIntlClientProvider>
    )
  ]
};

export default preview;
```

**Comment by stevensacks** [comment]
This is one of the consequences of using a canary build of React, which is what Next 15 has. React 19 is not officially released yet. Once it is, libraries will be updated, including this.

**Comment by ioExpander** [comment]
Hi. I'm currently facing a similar issue upgrading to next 15. However I've pinned React to version `18.3.1` 
Maybe it is a different issue. Can I help investigate ?

```
Error: A React Element from an older version of React was rendered. This is not supported. It can happen if:
  at reconcileChildFibersImpl (/vendors-node_modules_pnpm_storybook_react-dom-shim_8_4_2_react-dom_18_3_1_react_18_3_1__react-a77000.iframe.bundle.js:5384:11))
  at /vendors-node_modules_pnpm_storybook_react-dom-shim_8_4_2_react-dom_18_3_1_react_18_3_1__react-a77000.iframe.bundle.js:5423:33
  at reconcileChildren (/vendors-node_modules_pnpm_storybook_react-dom-shim_8_4_2_react-dom_18_3_1_react_18_3_1__react-a77000.iframe.bundle.js:7746:13))
  at updateFunctionComponent (/vendors-node_modules_pnpm_storybook_react-dom-shim_8_4_2_react-dom_18_3_1_react_18_3_1__react-a77000.iframe.bundle.js:8043:7))
```

**Comment by cfrerebeau** [comment]
This is happening on React 18.3.1. Next 15, support React 19 but does not force it.

**Comment by stevensacks** [comment]
This addon is already built on React 18.3.1. If you look in the package.json, you'll see it only has one peer dependency, and that's next-intl ^3. In the devDependencies, it is using the latest version 3.25.1 and it is working within the addon test harness.

The issue you're having is outside of this addon. There is no change that can be made to this addon that would fix that issue.

**Comment by stevensacks** [comment]
As suspected, Storybook is not fully compatible with Next 15, yet. They're working on it.

**Comment by CHC383** [comment]
I tried to look for React references in the distribution, and found out that there are `react.*` in `node_modules/storybook-next-intl/dist/preview.js`, such as `var A=b(n=>{var y=Symbol.for("react.element"),Q=Symbol.for("react.portal"),X=Symbol.for("react.fragment")...`

Specifically, it uses `react.element` which seems to be similar to this issue https://github.com/preactjs/signals/issues/580#issuecomment-2196321246, any idea how it gets bundled in to the distribution, and any idea how to support both React v18 and v19 without having to update the React in your dev dependencies?

I don't have enough knowledge here but it seems a lot of libraries were able to support multiple React versions including v19, so there got to be a way to make the generated code not specific to v18, maybe add React as a peer dependencies so  `react/cjs/react.production.min.js` is not included in the distribution (I might read this wrong)?

**Comment by robcaldecott** [comment]
Any chance we can get a release with this fix? Thanks!
